const ACTION_TYPES = {
    GET_PRODUCTS:"GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS:"GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_ERROR:"GET_PRODUCTS_ERROR",
    ADD_TO_CART: "ADD_TO_CART"
}

export default ACTION_TYPES